[package]
name = "vidium"
version = "0.1.0"
authors = ["Stanislav Panferov <stanislav@panferov.dev>"]
edition = "2021"
description = "Chrome video recording tool"
repository = "https://github.com/s-panferov/vidium"
license = "MIT OR Apache-2.0"
keywords = ["video", "browsers"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chromiumoxide = { version = "0.5.0", features = ["tokio-runtime"], default-features = false}
tokio = { version = "1.28.1", features = ["full"] }
futures= "0.3.28"
base64= "0.21.0"
video-rs = { version = "0.4.0", features = ["ndarray"] }
nshare = { version = "0.9.0", features = ["image", "ndarray"] }
image= "0.24.6"
ndarray= "0.15.6"
tracing= "0.1.37"
tracing-subscriber = "0.3.17"
tracing-timing= "0.6.0"
clap={version = "4.2.7", features=["derive"]}
